const INCREMENTO = 'INCREMENTO';
const DECREMENTO = 'DECREMENTO';
const INCREMENTO_IMPAR="INCREMENTO_IMPAR";
const DECREMENTO_ASYNC="DECREMENTO_ASYNC";

module.exports = {
  INCREMENTO,
  DECREMENTO,
  INCREMENTO_IMPAR,
  DECREMENTO_ASYNC
}